'use client';
import {ChangeEvent,useEffect,useMemo,useState} from 'react';
import AppShell from '@/components/AppShell';
import {Download,Plus,RefreshCw,Save,Search,Trash2,Upload} from 'lucide-react';
import {usePlanner} from '@/components/PlannerProvider';
import type {Hotel} from '@/lib/data';
import {destinations as destinationLibrary} from '@/lib/data';

const PAGE_SIZE=15;
const categoryOptions=['All','Budget','3 Star','4 Star Deluxe','4 Star Premium','5 Star Basic','5 Star','Unspecified'];
function draftFromHotel(h:Hotel){return {...h}}

export default function HotelDatabasePage(){
 const {hotelDatabase,updateHotelRecord,replaceHotelDatabase,addHotelRecord,deleteHotelRecord,resetHotelDatabase}=usePlanner();
 const [destination,setDestination]=useState('All');
 const [category,setCategory]=useState('All');
 const [query,setQuery]=useState('');
 const [onlyIncomplete,setOnlyIncomplete]=useState(false);
 const [page,setPage]=useState(1);
 const [editing,setEditing]=useState<Record<string,Hotel>>({});
 const [message,setMessage]=useState('');
 const [showAdd,setShowAdd]=useState(false);
 const [syncing,setSyncing]=useState(false);
 const [newHotel,setNewHotel]=useState({destination:'Srinagar',name:'',sourceCategory:'Custom',starRating:'',normalizedCategory:'Budget',mapB2B:'',extraBedB2B:'',cnbB2B:'',address:'',roomType:'',website:'',rateValidity:'October 2026',availabilityStatus:'Rate supplied; dated availability not confirmed',sourceType:'User entry'});
 const destinations=useMemo(()=>['All',...Array.from(new Set(hotelDatabase.map(h=>h.destination)))],[hotelDatabase]);
 const allDestinations=destinationLibrary.map(d=>d.name);
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('destination');if(requested&&allDestinations.includes(requested)){setDestination(requested);setPage(1);setNewHotel((x)=>({...x,destination:requested}))}},[allDestinations]);
 const filtered=useMemo(()=>hotelDatabase.filter(h=>{
   const matchesDest=destination==='All'||h.destination===destination;
   const matchesCat=category==='All'||h.normalizedCategory===category;
   const hay=`${h.name} ${h.destination} ${h.sourceCategory} ${h.address} ${h.roomType}`.toLowerCase();
   const matchesQuery=!query||hay.includes(query.toLowerCase());
   const incomplete=!onlyIncomplete||!h.address||!h.roomType||!h.mapB2B;
   return matchesDest&&matchesCat&&matchesQuery&&incomplete;
 }),[hotelDatabase,destination,category,query,onlyIncomplete]);
 const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));
 const shown=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
 function save(h:Hotel){updateHotelRecord(h.id,h);setEditing(e=>{const n={...e};delete n[h.id];return n});setMessage(`${h.name} saved.`);setTimeout(()=>setMessage(''),1800)}
 function edit(id:string,field:keyof Hotel,value:string|number|null){setEditing(e=>({...e,[id]:{...(e[id]||draftFromHotel(hotelDatabase.find(h=>h.id===id)!)),[field]:value}}));}
 function fieldValue(h:Hotel,key:keyof Hotel){return editing[h.id]?.[key]??h[key]}
 function exportDb(){const blob=new Blob([JSON.stringify(hotelDatabase,null,2)],{type:'application/json'});const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download='chakar-experience-hotel-database.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function importDb(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const arr=JSON.parse(String(reader.result));if(!Array.isArray(arr))throw new Error('Invalid database file.');replaceHotelDatabase(arr as Hotel[]);setMessage(`Imported ${arr.length} hotel records.`);}catch(err){setMessage(err instanceof Error?err.message:'Import failed.')}};reader.readAsText(file);e.target.value=''}
 async function refreshSnapshot(){setSyncing(true);try{const r=await fetch(`/api/hotels?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('Could not refresh the hotel snapshot.');const data=await r.json();if(!Array.isArray(data.hotels))throw new Error('Invalid hotel snapshot.');replaceHotelDatabase(data.hotels as Hotel[]);setMessage(`Refreshed ${data.count} hotel records from the current server snapshot.`);}catch(err){setMessage(err instanceof Error?err.message:'Refresh failed.')}finally{setSyncing(false)}}
 function createHotel(){if(!newHotel.name.trim())return;addHotelRecord({destination:newHotel.destination,name:newHotel.name.trim(),sourceCategory:newHotel.sourceCategory.trim()||'Custom',starRating:newHotel.starRating?Number(newHotel.starRating):null,normalizedCategory:newHotel.normalizedCategory,mapB2B:newHotel.mapB2B?Number(newHotel.mapB2B):null,extraBedB2B:newHotel.extraBedB2B?Number(newHotel.extraBedB2B):null,cnbB2B:newHotel.cnbB2B?Number(newHotel.cnbB2B):null,address:newHotel.address,roomType:newHotel.roomType,website:newHotel.website,sourceType:newHotel.sourceType,rateValidity:newHotel.rateValidity,availabilityStatus:newHotel.availabilityStatus,sourceFiles:['Platform entry'],notes:'Created from Chakar Experience Hotel Database Manager.'});setShowAdd(false);setNewHotel(v=>({...v,name:''}));setMessage('Hotel added.');setTimeout(()=>setMessage(''),1800)}
 const ratedCount=hotelDatabase.filter(h=>!!h.mapB2B).length;
 const destinationCoverage=allDestinations.filter(d=>hotelDatabase.some(h=>h.destination===d)).length;
 return <AppShell><main className="page"><div className="planner-heading"><div><span className="eyebrow">HOTEL DATABASE</span><h1>Manage the B2B hotel master.</h1><p>{hotelDatabase.length} hotel records across {destinationCoverage} of {allDestinations.length} library destinations. MAP, Extra Bed and CNB are internal B2B values. Address, room type and website are editable enrichment fields.</p></div><div className="heading-pill">B2B rates · internal only</div></div>
 <section className="db-kpi-grid"><div><span>Hotel records</span><b>{hotelDatabase.length}</b><small>Imported + custom entries</small></div><div><span>MAP B2B supplied</span><b>{ratedCount}</b><small>{hotelDatabase.length ? Math.round(ratedCount/hotelDatabase.length*100) : 0}% rate coverage</small></div><div><span>Database destinations</span><b>{destinationCoverage}</b><small>of {allDestinations.length} library destinations</small></div><div><span>Needs attention</span><b>{hotelDatabase.filter(h=>!h.mapB2B||!h.roomType||!h.address).length}</b><small>Missing rate or enrichment</small></div></section>
 <section className="db-banner"><div><b>B2B pricing stays inside Chakar.</b><span>Hotel database edits update the active trip immediately when the same hotel is selected. Customer PDFs receive only customer-facing hotel details and the final selling price.</span></div><div className="db-actions"><button className="secondary-link" onClick={exportDb}><Download size={14}/> Export database</button><label className="secondary-link"><Upload size={14}/> Import JSON<input hidden type="file" accept="application/json" onChange={importDb}/></label><button className="secondary-link" onClick={()=>setShowAdd(v=>!v)}><Plus size={14}/> Add hotel</button><button className="secondary-link" disabled={syncing} onClick={refreshSnapshot}><RefreshCw size={14}/> {syncing?'Refreshing...':'Refresh snapshot'}</button><button className="secondary-link" onClick={()=>{resetHotelDatabase();setMessage('Database reset to supplied B2B import.')}}><RefreshCw size={14}/> Reset import</button></div></section>
 {showAdd&&<section className="db-add-card"><div className="db-add-grid"><input placeholder="Hotel name" value={newHotel.name} onChange={e=>setNewHotel(x=>({...x,name:e.target.value}))}/><select value={newHotel.destination} onChange={e=>setNewHotel(x=>({...x,destination:e.target.value}))}>{allDestinations.map(d=><option key={d}>{d}</option>)}</select><select value={newHotel.normalizedCategory} onChange={e=>setNewHotel(x=>({...x,normalizedCategory:e.target.value}))}>{categoryOptions.slice(1).map(c=><option key={c}>{c}</option>)}</select><input type="number" placeholder="Star" min="0" max="5" value={newHotel.starRating} onChange={e=>setNewHotel(x=>({...x,starRating:e.target.value}))}/><input type="number" placeholder="MAP B2B" value={newHotel.mapB2B} onChange={e=>setNewHotel(x=>({...x,mapB2B:e.target.value}))}/><input type="number" placeholder="Extra bed B2B" value={newHotel.extraBedB2B} onChange={e=>setNewHotel(x=>({...x,extraBedB2B:e.target.value}))}/><input type="number" placeholder="CNB B2B" value={newHotel.cnbB2B} onChange={e=>setNewHotel(x=>({...x,cnbB2B:e.target.value}))}/><input placeholder="Address" value={newHotel.address} onChange={e=>setNewHotel(x=>({...x,address:e.target.value}))}/><input placeholder="Room type" value={newHotel.roomType} onChange={e=>setNewHotel(x=>({...x,roomType:e.target.value}))}/><button className="primary-cta inline" onClick={createHotel}><Save size={14}/> Save hotel</button></div></section>}
 <section className="db-summary-grid">{destinations.filter(d=>d!=='All').map(d=>{const rows=hotelDatabase.filter(h=>h.destination===d);const rated=rows.filter(h=>h.mapB2B).length;return <button type="button" className={destination===d?'db-summary-card active':'db-summary-card'} key={d} onClick={()=>{setDestination(d);setPage(1)}}><span>{d}</span><b>{rows.length}</b><small>{rated}/{rows.length} with MAP B2B</small></button>})}{allDestinations.filter(d=>!destinations.includes(d)).length>0&&<div className="db-summary-card empty"><span>Other library destinations</span><b>{allDestinations.filter(d=>!destinations.includes(d)).length}</b><small>No supplied hotel records yet</small></div>}</section>
 <section className="db-toolbar"><div className="filter-row">{destinations.map(d=><button key={d} className={destination===d?'filter active':'filter'} onClick={()=>{setDestination(d);setPage(1)}}>{d}</button>)}</div><div className="db-search"><label><Search size={13}/><input placeholder="Search hotel, destination or address" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}>{categoryOptions.map(c=><option key={c} value={c}>{c}</option>)}</select><label className="check-filter"><input type="checkbox" checked={onlyIncomplete} onChange={e=>{setOnlyIncomplete(e.target.checked);setPage(1)}}/> Needs attention</label></div></section>
 <div className="db-meta"><span>{filtered.length} records shown</span><span className="db-message">{message}</span><span>Page {page} / {pages}</span></div>
 <section className="db-table-wrap"><table className="db-table"><thead><tr><th>Destination</th><th>Hotel</th><th>Category</th><th>Stars</th><th>MAP B2B</th><th>Extra Bed</th><th>CNB</th><th>Address</th><th>Room Type</th><th>Website</th><th>Validity</th><th>Status</th><th>Save</th><th>Delete</th></tr></thead><tbody>{shown.map(h=>{const edited=editing[h.id];return <tr key={h.id}><td>{h.destination}</td><td><input value={String(fieldValue(h,'name')??'')} onChange={e=>edit(h.id,'name',e.target.value)}/></td><td><select value={String(fieldValue(h,'normalizedCategory')??'Unspecified')} onChange={e=>edit(h.id,'normalizedCategory',e.target.value)}>{categoryOptions.slice(1).map(c=><option key={c}>{c}</option>)}</select></td><td><input className="small-num" type="number" min="0" max="5" value={String(fieldValue(h,'starRating')??'')} onChange={e=>edit(h.id,'starRating',e.target.value===''?null:Number(e.target.value))}/></td><td><input className="money-cell" type="number" value={String(fieldValue(h,'mapB2B')??'')} onChange={e=>edit(h.id,'mapB2B',e.target.value===''?null:Number(e.target.value))}/></td><td><input className="money-cell" type="number" value={String(fieldValue(h,'extraBedB2B')??'')} onChange={e=>edit(h.id,'extraBedB2B',e.target.value===''?null:Number(e.target.value))}/></td><td><input className="money-cell" type="number" value={String(fieldValue(h,'cnbB2B')??'')} onChange={e=>edit(h.id,'cnbB2B',e.target.value===''?null:Number(e.target.value))}/></td><td><input value={String(fieldValue(h,'address')??'')} onChange={e=>edit(h.id,'address',e.target.value)}/></td><td><input value={String(fieldValue(h,'roomType')??'')} onChange={e=>edit(h.id,'roomType',e.target.value)}/></td><td><input value={String(fieldValue(h,'website')??'')} onChange={e=>edit(h.id,'website',e.target.value)}/></td><td><input value={String(fieldValue(h,'rateValidity')??'')} onChange={e=>edit(h.id,'rateValidity',e.target.value)}/></td><td><span className={h.mapB2B?'db-status supplied':'db-status missing'}>{h.mapB2B?'B2B rate supplied':'Rate missing'}</span></td><td><button className="icon-btn db-save" disabled={!edited} title="Save changes" onClick={()=>edited&&save(edited)}><Save size={13}/></button></td><td><button className="icon-btn db-delete" title="Delete record" onClick={()=>deleteHotelRecord(h.id)}><Trash2 size={13}/></button></td></tr>})}</tbody></table></section>
 <div className="pagination"><button className="secondary-link" disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><span>{page} / {pages}</span><button className="secondary-link" disabled={page>=pages} onClick={()=>setPage(p=>Math.min(pages,p+1))}>Next</button></div>
 </main></AppShell>
}
