'use client';
import {useMemo,useState,type ChangeEvent} from 'react';
import Link from 'next/link';
import {Building2,ChevronRight,Download,FileUp,Plus,Search,ShieldCheck} from 'lucide-react';
import type {Hotel} from '@/lib/data';
import {usePlanner} from '@/components/PlannerProvider';
type ImportRow={hotel:Hotel;action:'create'|'update'};
export default function HotelDashboard({initialHotels,configured,error:initialError}:{initialHotels:Hotel[];configured:boolean;error:string}){
  const [hotels,setHotels]=useState(initialHotels);const [search,setSearch]=useState('');const [destination,setDestination]=useState('All');const [error,setError]=useState(initialError);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [preview,setPreview]=useState<ImportRow[]|null>(null);const {replaceHotelDatabase}=usePlanner();
  const destinations=useMemo(()=>['All',...new Set(hotels.map(h=>h.destination))],[hotels]);
  const filtered=useMemo(()=>hotels.filter(h=>(destination==='All'||h.destination===destination)&&`${h.name} ${h.destination} ${h.normalizedCategory}`.toLowerCase().includes(search.toLowerCase())),[hotels,destination,search]);
  async function refresh(){const r=await fetch('/api/hotels',{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not refresh hotels.');setHotels(data.hotels);replaceHotelDatabase(data.hotels);}
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;setBusy(true);setError('');setPreview(null);try{const form=new FormData();form.append('file',file);const r=await fetch('/api/hotels/import',{method:'POST',body:form});const data=await r.json();if(!r.ok)throw new Error(data.error||'Import failed.');setPreview(data.records);setMessage(`${data.creates} new and ${data.updates} existing hotels found in ${file.name}. Review before applying.`);}catch(e){setError(e instanceof Error?e.message:'Import failed.')}finally{setBusy(false)}}
  async function apply(){if(!preview)return;setBusy(true);setError('');try{const r=await fetch('/api/hotels/import',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({records:preview})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not save import.');await refresh();setMessage(`${data.count} hotel records saved to the shared database.`);setPreview(null);}catch(e){setError(e instanceof Error?e.message:'Could not save import.')}finally{setBusy(false)}}
  async function downloadTemplate(){const {jsPDF}=await import('jspdf');const pdf=new jsPDF();pdf.setFont('helvetica','bold');pdf.setFontSize(17);pdf.text('Chakar Hotel Master PDF Template',18,22);pdf.setFont('helvetica','normal');pdf.setFontSize(10);pdf.text('Repeat one record block per hotel. Export the complete document as a text-based PDF.',18,32);const lines=['CHAKAR HOTEL RECORD','ID: hotel-001','Destination: Srinagar','Hotel: City Grace','Category: Budget','Stars: 3','MAP B2B: 2500','Extra Bed B2B: 800','CNB B2B: 600','Address: Dal Lake Road, Srinagar','Room Type: Deluxe','Website: https://example.com','Rate Validity: October 2026','Availability Status: Rate supplied; availability to confirm','END HOTEL'];pdf.setFont('courier','normal');pdf.setFontSize(10);pdf.text(lines,18,48);pdf.save('Chakar-Hotel-Master-Template.pdf');}
  const rated=hotels.filter(h=>h.mapB2B!==null).length;
  return <main className="page admin-page"><div className="admin-heading"><div><span className="eyebrow">PRIVATE HOTEL WORKSPACE</span><h1>Hotel dashboard</h1><p>Manage each hotel, its supplier rates and the details used by itinerary costing.</p></div><div className="admin-heading-actions"><span className="admin-security"><ShieldCheck size={16}/> Admin only</span><Link className="primary-cta inline" href="/hotels/new"><Plus size={16}/> Add hotel</Link></div></div>
    {!configured&&<div className="admin-alert">The shared database is not connected yet. Create the Supabase project and add its server credentials in Vercel. Hotel editing and PDF import will then be enabled.</div>}{error&&<div className="admin-alert">{error}</div>}{message&&<div className="admin-success">{message}</div>}
    <section className="admin-stats"><div><Building2 size={20}/><span>Hotels</span><b>{hotels.length}</b></div><div><span>Destinations</span><b>{destinations.length-1}</b></div><div><span>With B2B rate</span><b>{rated}</b></div><div><span>Need rate</span><b>{hotels.length-rated}</b></div></section>
    <section className="admin-import"><div><span className="eyebrow">BULK UPDATE</span><h2>Update hotels from one PDF</h2><p>Upload a text-based PDF using the hotel record format below. We match by hotel ID or destination and name, then show every proposed change before saving.</p></div><div className="admin-import-actions"><button className="secondary-link" onClick={downloadTemplate}><Download size={15}/> Sample PDF</button><label className="primary-cta inline admin-file-upload"><FileUp size={16}/>{busy?'Reading PDF…':'Upload hotel PDF'}<input className="admin-file-upload-input" type="file" accept="application/pdf,.pdf" onChange={upload} disabled={!configured||busy}/></label></div></section>
    <details className="admin-format"><summary>See the PDF record format</summary><p>Repeat this block for every hotel in one PDF. Keep the labels and include destination and hotel name. Add ID when updating an existing record.</p><pre>{`CHAKAR HOTEL RECORD\nID: hotel-001\nDestination: Srinagar\nHotel: City Grace\nCategory: Budget\nStars: 3\nMAP B2B: 2500\nExtra Bed B2B: 800\nCNB B2B: 600\nAddress: Dal Lake Road, Srinagar\nRoom Type: Deluxe\nWebsite: https://example.com\nRate Validity: October 2026\nAvailability Status: Rate supplied; availability to confirm\nEND HOTEL`}</pre><p>Scanned-image PDFs need OCR before upload. Keep each record on its own lines.</p></details>
    {preview&&<section className="admin-preview"><div className="admin-preview-head"><div><span className="eyebrow">REVIEW IMPORT</span><h2>{preview.length} hotel records ready</h2></div><div><button className="secondary-link" onClick={()=>setPreview(null)}>Cancel</button><button className="primary-cta inline" disabled={busy} onClick={apply}>Apply {preview.length} changes</button></div></div><div className="admin-preview-list">{preview.map(({hotel,action})=><div key={hotel.id}><span className={action==='create'?'db-status supplied':'db-status'}>{action}</span><b>{hotel.name}</b><small>{hotel.destination} · {hotel.normalizedCategory} · MAP {hotel.mapB2B===null?'—':`₹${hotel.mapB2B}`}</small></div>)}</div></section>}
    <section className="admin-catalog"><div className="admin-catalog-head"><div><span className="eyebrow">HOTEL RECORDS</span><h2>Browse the master</h2></div><span>{filtered.length} shown</span></div><div className="admin-toolbar"><label><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search hotel or category"/></label><select value={destination} onChange={e=>setDestination(e.target.value)}>{destinations.map(d=><option key={d}>{d}</option>)}</select></div><div className="admin-hotel-list">{filtered.map(h=><Link key={h.id} className="admin-hotel-row" href={`/hotels/${encodeURIComponent(h.id)}`}><div className="admin-hotel-avatar">{h.name.slice(0,1).toUpperCase()}</div><div><b>{h.name}</b><span>{h.destination} · {h.normalizedCategory}</span></div><div className="admin-hotel-rate">{h.mapB2B===null?'Rate missing':`₹${h.mapB2B.toLocaleString('en-IN')} MAP`}</div><ChevronRight size={18}/></Link>)}{!filtered.length&&<p className="admin-empty">No hotels match this view. Add a hotel or import your master PDF.</p>}</div></section>
  </main>;
}
