'use client';
import Link from 'next/link';
import { useMemo } from 'react';
import { ChevronLeft, ChevronRight, LockKeyhole, WalletCards } from 'lucide-react';
import AppShell from '@/components/AppShell';
import PlannerChrome from '@/components/PlannerChrome';
import { usePlanner } from '@/components/PlannerProvider';
import { calculateCosts } from '@/lib/costing';
import { paymentAmounts } from '@/lib/pricing';
function money(v:number){return `₹${Math.round(v).toLocaleString('en-IN')}`}
const PROFIT_PRESETS=[5,8,10,12,15,20,25];
export default function CostingPage(){
 const {plan,hotelSelections,costModel,setCostModel,input,paymentPlan,selectPaymentPlan,setPaymentPercentage}=usePlanner();
 const costs=useMemo(()=>plan?calculateCosts(plan,hotelSelections,costModel):null,[plan,hotelSelections,costModel]);
 if(!plan||!costs)return <AppShell><PlannerChrome title="Costing" eyebrow="STEP 03 · COSTING"><div className="empty-panel"><WalletCards size={28}/><h2>Complete the itinerary and hotels first.</h2><Link className="primary-cta inline" href="/"><ChevronRight size={16}/> Build Your Trip</Link></div></PlannerChrome></AppShell>;
 const groupBudget=(input.budget||0)*costs.people; const within=groupBudget===0||costs.sellingTotal<=groupBudget;
 const activeSchedule=paymentPlan[paymentPlan.selected];
 const installments=paymentAmounts(costs.sellingTotal,activeSchedule.booking,activeSchedule.arrival);
 return <AppShell><PlannerChrome title="Trip costing" eyebrow="STEP 03 · COSTING">
  <section className="cost-summary"><div><span className="eyebrow">CUSTOMER SELLING TOTAL</span><h2>{money(costs.sellingTotal)}</h2><p>Accommodation + transport + other costs, then your custom markup, 5% GST and the final customer total. Internal rates are omitted from the client PDF.</p></div><div className={within?'budget-status ok':'budget-status warn'}><span>Budget / person</span><b>{input.budget?money(input.budget):'No cap'}</b><small>{groupBudget?`${within?'Within':'Above'} group reference · ${money(groupBudget)}`:'No budget cap'}</small></div></section>
  <div className="cost-grid four-columns">
   <article className="cost-card"><div className="cost-card-title"><h3>Accommodation</h3><span>From Hotels</span></div>{hotelSelections.map(h=><div className="cost-line" key={h.location}><span>{h.location} · {h.hotelName}<small>{h.nights}N × {h.rooms} room · {h.extraBeds} extra bed · {h.cnb} CNB</small></span><b>{money(h.nights*h.rooms*h.nightlyRate+h.nights*h.extraBeds*h.extraBedRate+h.nights*h.cnb*h.cnbRate)}</b></div>)}<div className="cost-total-line"><span>Accommodation</span><b>{money(costs.accommodation)}</b></div></article>
   <article className="cost-card"><div className="cost-card-title"><h3>Transport</h3><span>Internal service cost</span></div><div className="edit-cost"><label>Transport / charged day</label><div><span>₹</span><input type="number" min="0" value={Math.round(costModel.transportDaily)} onChange={e=>setCostModel({transportDaily:Math.max(0,+e.target.value||0)})}/></div></div><div className="cost-line"><span>{costs.vehicleDays} charged service day(s)</span><b>{money(costs.transport)}</b></div></article>
   <article className="cost-card"><div className="cost-card-title"><h3>Others</h3><span>Additional package costs</span></div><div className="edit-cost"><label>Other amount</label><div><span>₹</span><input type="number" min="0" value={Math.round(costModel.otherAmount)} onChange={e=>setCostModel({otherAmount:Math.max(0,+e.target.value||0)})}/></div><small>Use for any additional internal package item.</small></div><div className="cost-line"><span>Others subtotal<small>Only additional internal package costs</small></span><b>{money(costs.other)}</b></div></article>
  </div>
  <section className="selling-range-box"><div><span>Customer selling range</span><b>{money(costs.low)} – {money(costs.high)}</b><small>Reference range before custom profit / markup and GST.</small></div><div><span>Cost before markup</span><b>{money(costs.preGst)}</b><small>Accommodation + transport + others.</small></div></section>
  <section className="profit-strip"><div><div className="profit-lock"><LockKeyhole size={14}/><span>INTERNAL PROFIT / MARKUP</span></div><h3>Profit and markup</h3><p>Private operator control. This value is not printed in the client PDF.</p></div><div className="profit-controls"><div className="profit-presets">{PROFIT_PRESETS.map(v=><button key={v} className={costModel.profitPct===v?'profit-preset active':'profit-preset'} onClick={()=>setCostModel({profitPct:v})}>{v}%</button>)}<label className="custom-profit"><span>Custom</span><input type="number" min="0" max="100" step="0.5" value={costModel.profitPct} onChange={e=>setCostModel({profitPct:Math.max(0,Math.min(100,+e.target.value||0))})}/><b>%</b></label></div><div className="profit-readout"><span>Cost before markup</span><b>{money(costs.preGst)}</b><span>Profit at {costModel.profitPct}%</span><strong>{money(costs.profit)}</strong><span>Subtotal after markup</span><b>{money(costs.subtotalAfterMarkup)}</b></div></div></section>
  <section className="cost-card gst-final-card"><div className="cost-card-title"><h3>GST</h3><span>Applied after profit / markup</span></div><div className="gst-final-row"><div><span>Subtotal after markup</span><b>{money(costs.subtotalAfterMarkup)}</b></div><div><span>GST @ 5%</span><b>{money(costs.gst)}</b></div><div className="final-total"><span>Final customer total</span><strong>{money(costs.sellingTotal)}</strong></div></div></section>
  <section className="payment-plan-card"><div className="cost-card-title"><h3>Payment plan</h3><span>Customer instalments from the final selling total</span></div><div className="payment-plan-options">{(['one','two'] as const).map((key)=>{const schedule=paymentPlan[key];return <button type="button" key={key} className={paymentPlan.selected===key?'active':''} aria-pressed={paymentPlan.selected===key} onClick={()=>selectPaymentPlan(key)}>Plan {key==='one'?'One':'Two'}<small>{schedule.booking}% booking · {schedule.arrival}% arrival · {100-schedule.booking-schedule.arrival}% during trip</small></button>})}</div><div className="payment-plan-editor"><label>At booking %<input type="number" min="0" max={100-activeSchedule.arrival} value={activeSchedule.booking} onChange={(e)=>setPaymentPercentage(paymentPlan.selected,'booking',Number(e.target.value))}/></label><label>On arrival %<input type="number" min="0" max={100-activeSchedule.booking} value={activeSchedule.arrival} onChange={(e)=>setPaymentPercentage(paymentPlan.selected,'arrival',Number(e.target.value))}/></label><div><span>During trip</span><b>{installments.duringPct}%</b></div></div><div className="payment-amount-grid"><div><span>At booking</span><b>{money(installments.booking)}</b></div><div><span>On arrival</span><b>{money(installments.arrival)}</b></div><div><span>During trip</span><b>{money(installments.during)}</b></div></div></section>
  {costs.missingHotelRates.length>0&&<div className="cost-warning"><LockKeyhole size={14}/><span><b>Hotel costing incomplete.</b> Missing/zero room rate: {costs.missingHotelRates.join(', ')}. You can type a custom hotel and its internal rate in Hotels.</span></div>}
  <div className="next-row"><Link className="secondary-link" href="/planner/hotels"><ChevronLeft size={16}/> Back to hotels</Link><div><b>Costing complete?</b><span>Preview the customer PDF next.</span></div><Link className="primary-cta inline" href="/planner/pdf">Next: Client PDF <ChevronRight size={16}/></Link></div>
 </PlannerChrome></AppShell>
}
